# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/boards/latest/
Accept: application/json

###

GET http://127.0.0.1:8000/boards/
Accept: application/json

###

GET http://127.0.0.1:8000/boardlist/
Accept: application/json

###

GET http://127.0.0.1:8000/{{tag}}
Accept: application/json

###

GET http://127.0.0.1:8000/sfw_boards/
Accept: application/json

###

GET http://127.0.0.1:8000/categories/
Accept: application/json

###

GET http://127.0.0.1:8000/boards/{{board_id}}/posts/
Accept: application/json

###

GET http://127.0.0.1:8000/{{tag}}/ops
Accept: application/json

###

